# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.0

jobs:
  jest-tests:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13.1"
      # Compile Editor
      - run:
          name: Clone editor repository
          command: >-
            git clone https://github.com/essential-randomness/boba-editor
      - run:
          name: see files
          command: ls -la
      - node/install-packages:
          pkg-manager: yarn
          app-dir: boba-editor
      - run:
          name: build editor
          working_directory: boba-editor
          command: yarn run build
      - run:
          name: create editor link
          working_directory: boba-editor
          command: yarn link
      # Compile UI
      - run:
          name: Clone ui repository
          command: >-
            git clone https://github.com/essential-randomness/bobaboard-ui.git
      - node/install-packages:
          pkg-manager: yarn
          app-dir: bobaboard-ui
      - run:
          name: link editor
          command: yarn link @bobaboard/boba-editor
          working_directory: bobaboard-ui
      - run:
          name: build ui
          working_directory: bobaboard-ui
          command: yarn run build
      - run:
          name: create ui link
          working_directory: bobaboard-ui
          command: yarn link
      ## frontend
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: link ui
          command: yarn link @bobaboard/ui-components
      - run:
          name: test
          command: yarn run test:ci
  e2e-tests:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.13.1"
      # Compile Editor
      - run:
          name: Clone editor repository
          command: >-
            git clone https://github.com/essential-randomness/boba-editor
      - run:
          name: see files
          command: ls -la
      - node/install-packages:
          pkg-manager: yarn
          app-dir: boba-editor
      - run:
          name: build editor
          working_directory: boba-editor
          command: yarn run build
      - run:
          name: create editor link
          working_directory: boba-editor
          command: yarn link
      # Compile UI
      - run:
          name: Clone ui repository
          command: >-
            git clone https://github.com/essential-randomness/bobaboard-ui.git
      - node/install-packages:
          pkg-manager: yarn
          app-dir: bobaboard-ui
      - run:
          name: link editor
          command: yarn link @bobaboard/boba-editor
          working_directory: bobaboard-ui
      - run:
          name: build ui
          working_directory: bobaboard-ui
          command: yarn run build
      - run:
          name: create ui link
          working_directory: bobaboard-ui
          command: yarn link
      ## frontend
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: link ui
          command: yarn link @bobaboard/ui-components
      - run:
          name: Add twisted-minds_boba.local
          command: |
            sudo tee -a /etc/hosts \<<<'127.0.0.1 twisted-minds_boba.local'
            cat /etc/hosts
      - run:
          name: test
          command: yarn run test:e2e:ci

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  tests:
    jobs:
      - jest-tests
      - e2e-tests